config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
              path: :gurus,
              path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'sessions' }
  devise_for :admins, path: :admin


  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: :true, except: :index do
        resources :answers, shallow: :true, except: :index
      end
    end
  end
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: :true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_question, only: [:show, :destroy, :edit, :update]
  before_action :find_test, only: [:new, :create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_not_found

  def show; end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_not_found
    render 'shared/_page_not_found'
  end

  def find_test
    @test = Test.find(params[:test_id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  
  def question_form_header(question)
    if question.persisted?
      "Edit question #{question.body}"
    else
      'Add new question' 
    end
  end

end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>

<%= render 'shared/errors', resource: @question %>

<p>
  <%= form.label :body %>
  <%= form.text_field :body, id: :question_body %>
</p>

<p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'Show', admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
  <td>
    <%= link_to 'Delete',
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<h3><%= question_form_header(@question) %></h3>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<h3><%= question_form_header(@question) %></h3>

<%= render 'form' %>
<%= link_to 'Back', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<p>
  <strong>Question body:</strong>
  <%= @question.body %>
</p>

<h4>Answers:</h4>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Back', admin_test_path(@question.test) %>